# ---- Build stage ----
FROM golang:1.25-alpine AS builder

ARG GIT_COMMIT
ARG GIT_DATE
ARG GIT_TAG

WORKDIR /workdir

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
  go build -ldflags "\
    -w -s \
    -X 'main.gitCommit=${GIT_COMMIT}' \
    -X 'main.gitDate=${GIT_DATE}' \
    -X 'main.gitTag=${GIT_TAG}'" \
  -o mcrunner main.go

# ----- Manager image -----
FROM registry.mineviet.com/mcmanager:latest AS web

# ---- Runtime stage ----
FROM eclipse-temurin:17-jre-alpine 
RUN apk add --no-cache \
  ca-certificates \
  tzdata \
  dcron \
  && update-ca-certificates

WORKDIR /minecraft

COPY --from=builder /workdir/mcrunner /usr/bin/mcrunner
COPY --from=web /app/dist /dist

COPY ./docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000 25565

ENTRYPOINT ["/entrypoint.sh", "--staticdir=/dist"]
