// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: mcrunner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_RUNNING  Status = 1
	Status_STATUS_STOPPING Status = 2
	Status_STATUS_STOPPED  Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_RUNNING",
		2: "STATUS_STOPPING",
		3: "STATUS_STOPPED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_RUNNING":  1,
		"STATUS_STOPPING": 2,
		"STATUS_STOPPED":  3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_mcrunner_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_mcrunner_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{0}
}

type PtyBuffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyBuffer) Reset() {
	*x = PtyBuffer{}
	mi := &file_mcrunner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyBuffer) ProtoMessage() {}

func (x *PtyBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyBuffer.ProtoReflect.Descriptor instead.
func (*PtyBuffer) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{0}
}

func (x *PtyBuffer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PtyResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyResize) Reset() {
	*x = PtyResize{}
	mi := &file_mcrunner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyResize) ProtoMessage() {}

func (x *PtyResize) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyResize.ProtoReflect.Descriptor instead.
func (*PtyResize) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{1}
}

func (x *PtyResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *PtyResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type PtyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyStatus) Reset() {
	*x = PtyStatus{}
	mi := &file_mcrunner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyStatus) ProtoMessage() {}

func (x *PtyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyStatus.ProtoReflect.Descriptor instead.
func (*PtyStatus) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{2}
}

func (x *PtyStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

type PtyError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyError) Reset() {
	*x = PtyError{}
	mi := &file_mcrunner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyError) ProtoMessage() {}

func (x *PtyError) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyError.ProtoReflect.Descriptor instead.
func (*PtyError) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{3}
}

func (x *PtyError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PtyError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Tps           float64                `protobuf:"fixed64,3,opt,name=tps,proto3" json:"tps,omitempty"`
	MemoryUsage   uint64                 `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryLimit   uint64                 `protobuf:"varint,5,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	CpuLimit      float64                `protobuf:"fixed64,7,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	UptimeSec     uint64                 `protobuf:"varint,8,opt,name=uptime_sec,json=uptimeSec,proto3" json:"uptime_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_mcrunner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{4}
}

func (x *ServerState) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *ServerState) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ServerState) GetTps() float64 {
	if x != nil {
		return x.Tps
	}
	return 0
}

func (x *ServerState) GetMemoryUsage() uint64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *ServerState) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ServerState) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *ServerState) GetCpuLimit() float64 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *ServerState) GetUptimeSec() uint64 {
	if x != nil {
		return x.UptimeSec
	}
	return 0
}

// ConsoleMessage multiplexes PTY data and resize events in a single bidi stream
type ConsoleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConsoleMessage_PtyError
	//	*ConsoleMessage_PtyBuffer
	//	*ConsoleMessage_PtyResize
	//	*ConsoleMessage_PtyStatus
	Payload       isConsoleMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleMessage) Reset() {
	*x = ConsoleMessage{}
	mi := &file_mcrunner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleMessage) ProtoMessage() {}

func (x *ConsoleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleMessage.ProtoReflect.Descriptor instead.
func (*ConsoleMessage) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{5}
}

func (x *ConsoleMessage) GetPayload() isConsoleMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConsoleMessage) GetPtyError() *PtyError {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleMessage_PtyError); ok {
			return x.PtyError
		}
	}
	return nil
}

func (x *ConsoleMessage) GetPtyBuffer() *PtyBuffer {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleMessage_PtyBuffer); ok {
			return x.PtyBuffer
		}
	}
	return nil
}

func (x *ConsoleMessage) GetPtyResize() *PtyResize {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleMessage_PtyResize); ok {
			return x.PtyResize
		}
	}
	return nil
}

func (x *ConsoleMessage) GetPtyStatus() *PtyStatus {
	if x != nil {
		if x, ok := x.Payload.(*ConsoleMessage_PtyStatus); ok {
			return x.PtyStatus
		}
	}
	return nil
}

type isConsoleMessage_Payload interface {
	isConsoleMessage_Payload()
}

type ConsoleMessage_PtyError struct {
	PtyError *PtyError `protobuf:"bytes,1,opt,name=pty_error,json=ptyError,proto3,oneof"`
}

type ConsoleMessage_PtyBuffer struct {
	PtyBuffer *PtyBuffer `protobuf:"bytes,2,opt,name=pty_buffer,json=ptyBuffer,proto3,oneof"`
}

type ConsoleMessage_PtyResize struct {
	PtyResize *PtyResize `protobuf:"bytes,3,opt,name=pty_resize,json=ptyResize,proto3,oneof"`
}

type ConsoleMessage_PtyStatus struct {
	PtyStatus *PtyStatus `protobuf:"bytes,4,opt,name=pty_status,json=ptyStatus,proto3,oneof"`
}

func (*ConsoleMessage_PtyError) isConsoleMessage_Payload() {}

func (*ConsoleMessage_PtyBuffer) isConsoleMessage_Payload() {}

func (*ConsoleMessage_PtyResize) isConsoleMessage_Payload() {}

func (*ConsoleMessage_PtyStatus) isConsoleMessage_Payload() {}

type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_mcrunner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mcrunner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_mcrunner_proto_rawDescGZIP(), []int{6}
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

var File_mcrunner_proto protoreflect.FileDescriptor

const file_mcrunner_proto_rawDesc = "" +
	"\n" +
	"\x0emcrunner.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n" +
	"\tPtyBuffer\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"3\n" +
	"\tPtyResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\",\n" +
	"\tPtyStatus\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x0e2\a.StatusR\x06status\"8\n" +
	"\bPtyError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf1\x01\n" +
	"\vServerState\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12\x10\n" +
	"\x03tps\x18\x03 \x01(\x01R\x03tps\x12!\n" +
	"\fmemory_usage\x18\x04 \x01(\x04R\vmemoryUsage\x12!\n" +
	"\fmemory_limit\x18\x05 \x01(\x04R\vmemoryLimit\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\bcpuUsage\x12\x1b\n" +
	"\tcpu_limit\x18\a \x01(\x01R\bcpuLimit\x12\x1d\n" +
	"\n" +
	"uptime_sec\x18\b \x01(\x04R\tuptimeSec\"\xcc\x01\n" +
	"\x0eConsoleMessage\x12(\n" +
	"\tpty_error\x18\x01 \x01(\v2\t.PtyErrorH\x00R\bptyError\x12+\n" +
	"\n" +
	"pty_buffer\x18\x02 \x01(\v2\n" +
	".PtyBufferH\x00R\tptyBuffer\x12+\n" +
	"\n" +
	"pty_resize\x18\x03 \x01(\v2\n" +
	".PtyResizeH\x00R\tptyResize\x12+\n" +
	"\n" +
	"pty_status\x18\x04 \x01(\v2\n" +
	".PtyStatusH\x00R\tptyStatusB\t\n" +
	"\apayload\"*\n" +
	"\x0eCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand*Y\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_STOPPING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_STOPPED\x10\x032\x93\x04\n" +
	"\bMCRunner\x12=\n" +
	"\vStartServer\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"StopServer\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"KillServer\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rRestartServer\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x120\n" +
	"\bGetState\x12\x16.google.protobuf.Empty\x1a\f.ServerState\x126\n" +
	"\vSendCommand\x12\x0f.CommandRequest\x1a\x16.google.protobuf.Empty\x123\n" +
	"\rResizeConsole\x12\n" +
	".PtyResize\x1a\x16.google.protobuf.Empty\x125\n" +
	"\rStreamConsole\x12\x0f.ConsoleMessage\x1a\x0f.ConsoleMessage(\x010\x01\x125\n" +
	"\vStreamState\x12\x16.google.protobuf.Empty\x1a\f.ServerState0\x01B-Z+github.com/khanghh/mcrunner/pkg/proto;protob\x06proto3"

var (
	file_mcrunner_proto_rawDescOnce sync.Once
	file_mcrunner_proto_rawDescData []byte
)

func file_mcrunner_proto_rawDescGZIP() []byte {
	file_mcrunner_proto_rawDescOnce.Do(func() {
		file_mcrunner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcrunner_proto_rawDesc), len(file_mcrunner_proto_rawDesc)))
	})
	return file_mcrunner_proto_rawDescData
}

var file_mcrunner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mcrunner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mcrunner_proto_goTypes = []any{
	(Status)(0),            // 0: Status
	(*PtyBuffer)(nil),      // 1: PtyBuffer
	(*PtyResize)(nil),      // 2: PtyResize
	(*PtyStatus)(nil),      // 3: PtyStatus
	(*PtyError)(nil),       // 4: PtyError
	(*ServerState)(nil),    // 5: ServerState
	(*ConsoleMessage)(nil), // 6: ConsoleMessage
	(*CommandRequest)(nil), // 7: CommandRequest
	(*emptypb.Empty)(nil),  // 8: google.protobuf.Empty
}
var file_mcrunner_proto_depIdxs = []int32{
	0,  // 0: PtyStatus.status:type_name -> Status
	0,  // 1: ServerState.status:type_name -> Status
	4,  // 2: ConsoleMessage.pty_error:type_name -> PtyError
	1,  // 3: ConsoleMessage.pty_buffer:type_name -> PtyBuffer
	2,  // 4: ConsoleMessage.pty_resize:type_name -> PtyResize
	3,  // 5: ConsoleMessage.pty_status:type_name -> PtyStatus
	8,  // 6: MCRunner.StartServer:input_type -> google.protobuf.Empty
	8,  // 7: MCRunner.StopServer:input_type -> google.protobuf.Empty
	8,  // 8: MCRunner.KillServer:input_type -> google.protobuf.Empty
	8,  // 9: MCRunner.RestartServer:input_type -> google.protobuf.Empty
	8,  // 10: MCRunner.GetState:input_type -> google.protobuf.Empty
	7,  // 11: MCRunner.SendCommand:input_type -> CommandRequest
	2,  // 12: MCRunner.ResizeConsole:input_type -> PtyResize
	6,  // 13: MCRunner.StreamConsole:input_type -> ConsoleMessage
	8,  // 14: MCRunner.StreamState:input_type -> google.protobuf.Empty
	8,  // 15: MCRunner.StartServer:output_type -> google.protobuf.Empty
	8,  // 16: MCRunner.StopServer:output_type -> google.protobuf.Empty
	8,  // 17: MCRunner.KillServer:output_type -> google.protobuf.Empty
	8,  // 18: MCRunner.RestartServer:output_type -> google.protobuf.Empty
	5,  // 19: MCRunner.GetState:output_type -> ServerState
	8,  // 20: MCRunner.SendCommand:output_type -> google.protobuf.Empty
	8,  // 21: MCRunner.ResizeConsole:output_type -> google.protobuf.Empty
	6,  // 22: MCRunner.StreamConsole:output_type -> ConsoleMessage
	5,  // 23: MCRunner.StreamState:output_type -> ServerState
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_mcrunner_proto_init() }
func file_mcrunner_proto_init() {
	if File_mcrunner_proto != nil {
		return
	}
	file_mcrunner_proto_msgTypes[5].OneofWrappers = []any{
		(*ConsoleMessage_PtyError)(nil),
		(*ConsoleMessage_PtyBuffer)(nil),
		(*ConsoleMessage_PtyResize)(nil),
		(*ConsoleMessage_PtyStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcrunner_proto_rawDesc), len(file_mcrunner_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcrunner_proto_goTypes,
		DependencyIndexes: file_mcrunner_proto_depIdxs,
		EnumInfos:         file_mcrunner_proto_enumTypes,
		MessageInfos:      file_mcrunner_proto_msgTypes,
	}.Build()
	File_mcrunner_proto = out.File
	file_mcrunner_proto_goTypes = nil
	file_mcrunner_proto_depIdxs = nil
}
