// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: mcrunner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MCRunner_StartServer_FullMethodName   = "/MCRunner/StartServer"
	MCRunner_StopServer_FullMethodName    = "/MCRunner/StopServer"
	MCRunner_KillServer_FullMethodName    = "/MCRunner/KillServer"
	MCRunner_RestartServer_FullMethodName = "/MCRunner/RestartServer"
	MCRunner_GetState_FullMethodName      = "/MCRunner/GetState"
	MCRunner_SendCommand_FullMethodName   = "/MCRunner/SendCommand"
	MCRunner_ResizeConsole_FullMethodName = "/MCRunner/ResizeConsole"
	MCRunner_StreamConsole_FullMethodName = "/MCRunner/StreamConsole"
	MCRunner_StreamState_FullMethodName   = "/MCRunner/StreamState"
)

// MCRunnerClient is the client API for MCRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ===== gRPC services =====
type MCRunnerClient interface {
	// Lifecycle controls
	StartServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StopServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KillServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RestartServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Server state
	GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerState, error)
	// Console commands
	SendCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResizeConsole(ctx context.Context, in *PtyResize, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Streams live console output and state
	StreamConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleMessage, ConsoleMessage], error)
	StreamState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerState], error)
}

type mCRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewMCRunnerClient(cc grpc.ClientConnInterface) MCRunnerClient {
	return &mCRunnerClient{cc}
}

func (c *mCRunnerClient) StartServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCRunner_StartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) StopServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCRunner_StopServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) KillServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCRunner_KillServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) RestartServer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCRunner_RestartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) GetState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, MCRunner_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) SendCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCRunner_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) ResizeConsole(ctx context.Context, in *PtyResize, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MCRunner_ResizeConsole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mCRunnerClient) StreamConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsoleMessage, ConsoleMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MCRunner_ServiceDesc.Streams[0], MCRunner_StreamConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsoleMessage, ConsoleMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCRunner_StreamConsoleClient = grpc.BidiStreamingClient[ConsoleMessage, ConsoleMessage]

func (c *mCRunnerClient) StreamState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ServerState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MCRunner_ServiceDesc.Streams[1], MCRunner_StreamState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ServerState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCRunner_StreamStateClient = grpc.ServerStreamingClient[ServerState]

// MCRunnerServer is the server API for MCRunner service.
// All implementations must embed UnimplementedMCRunnerServer
// for forward compatibility.
//
// ===== gRPC services =====
type MCRunnerServer interface {
	// Lifecycle controls
	StartServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	StopServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	KillServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	RestartServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Server state
	GetState(context.Context, *emptypb.Empty) (*ServerState, error)
	// Console commands
	SendCommand(context.Context, *CommandRequest) (*emptypb.Empty, error)
	ResizeConsole(context.Context, *PtyResize) (*emptypb.Empty, error)
	// Streams live console output and state
	StreamConsole(grpc.BidiStreamingServer[ConsoleMessage, ConsoleMessage]) error
	StreamState(*emptypb.Empty, grpc.ServerStreamingServer[ServerState]) error
	mustEmbedUnimplementedMCRunnerServer()
}

// UnimplementedMCRunnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMCRunnerServer struct{}

func (UnimplementedMCRunnerServer) StartServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartServer not implemented")
}
func (UnimplementedMCRunnerServer) StopServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServer not implemented")
}
func (UnimplementedMCRunnerServer) KillServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KillServer not implemented")
}
func (UnimplementedMCRunnerServer) RestartServer(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartServer not implemented")
}
func (UnimplementedMCRunnerServer) GetState(context.Context, *emptypb.Empty) (*ServerState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedMCRunnerServer) SendCommand(context.Context, *CommandRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedMCRunnerServer) ResizeConsole(context.Context, *PtyResize) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResizeConsole not implemented")
}
func (UnimplementedMCRunnerServer) StreamConsole(grpc.BidiStreamingServer[ConsoleMessage, ConsoleMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamConsole not implemented")
}
func (UnimplementedMCRunnerServer) StreamState(*emptypb.Empty, grpc.ServerStreamingServer[ServerState]) error {
	return status.Errorf(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedMCRunnerServer) mustEmbedUnimplementedMCRunnerServer() {}
func (UnimplementedMCRunnerServer) testEmbeddedByValue()                  {}

// UnsafeMCRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MCRunnerServer will
// result in compilation errors.
type UnsafeMCRunnerServer interface {
	mustEmbedUnimplementedMCRunnerServer()
}

func RegisterMCRunnerServer(s grpc.ServiceRegistrar, srv MCRunnerServer) {
	// If the following call pancis, it indicates UnimplementedMCRunnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MCRunner_ServiceDesc, srv)
}

func _MCRunner_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_StartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).StartServer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_StopServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).StopServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_StopServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).StopServer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_KillServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).KillServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_KillServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).KillServer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_RestartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).RestartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_RestartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).RestartServer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).GetState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).SendCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_ResizeConsole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PtyResize)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MCRunnerServer).ResizeConsole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MCRunner_ResizeConsole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MCRunnerServer).ResizeConsole(ctx, req.(*PtyResize))
	}
	return interceptor(ctx, in, info, handler)
}

func _MCRunner_StreamConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MCRunnerServer).StreamConsole(&grpc.GenericServerStream[ConsoleMessage, ConsoleMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCRunner_StreamConsoleServer = grpc.BidiStreamingServer[ConsoleMessage, ConsoleMessage]

func _MCRunner_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MCRunnerServer).StreamState(m, &grpc.GenericServerStream[emptypb.Empty, ServerState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MCRunner_StreamStateServer = grpc.ServerStreamingServer[ServerState]

// MCRunner_ServiceDesc is the grpc.ServiceDesc for MCRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MCRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "MCRunner",
	HandlerType: (*MCRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartServer",
			Handler:    _MCRunner_StartServer_Handler,
		},
		{
			MethodName: "StopServer",
			Handler:    _MCRunner_StopServer_Handler,
		},
		{
			MethodName: "KillServer",
			Handler:    _MCRunner_KillServer_Handler,
		},
		{
			MethodName: "RestartServer",
			Handler:    _MCRunner_RestartServer_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _MCRunner_GetState_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _MCRunner_SendCommand_Handler,
		},
		{
			MethodName: "ResizeConsole",
			Handler:    _MCRunner_ResizeConsole_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConsole",
			Handler:       _MCRunner_StreamConsole_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamState",
			Handler:       _MCRunner_StreamState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mcrunner.proto",
}
